repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: python
        language_version: python3.12
        args: [
          '--config=ruff.toml'
        ]
        entry: 'ruff check'
        files: ^src/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        language_version: python3.12
        args: [
          '--config-file=mypy.ini'
        ]
        files: ^src/
        types_or: [python, pyi]
        entry: 'mypy'
