stages:
  - trigger
  - lint
  - check-build
  - semantic-release
  - build
  - deploy

include:
  - local: "/.gitlab/extends/lint.yml"
  - local: "/.gitlab/extends/check-build.yml"
  - local: "/.gitlab/extends/semantic-release.yml"
  - local: "/.gitlab/extends/build.yml"
  - local: "/.gitlab/extends/deploy.yml"


workflow:
  rules:
    # Коммит выполненный в ветке main
    - if: '$CI_COMMIT_BRANCH == "main"'
    # Pipeline в контексте MR
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Если контекст commit-а, но есть открытый MR, то НЕ запускаемся
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never


auth:
  stage: trigger
  trigger:
    include:
      - local: "/.gitlab/auth.yml"
    # Родительский pipeline ждет выполнения всех дочерних
    strategy: depend
    forward:
      # Переменные CI, например, секреты
      pipeline_variables: true
      # Переменные из глобального блока variables
      yaml_variables: true
