.build:image:
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [ "" ]

.build:script:
  before_script:
    - echo "Building image with version ${VERSION}"
  script:
    - /kaniko/executor
      --context $PATH_WORKING_DIR
      --dockerfile $PATH_DOCKER_FILE
      --destination $APP_IMAGE
      --destination $APP_IMAGE_LATEST

.build:retry:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.build:only-main:when-manual:
  only:
    - main
  when: manual
